name: CraftControl
version: '1.1'
author: Zeppy
main: me.zeppy.craftControl.CraftControl
api-version: '1.21'

commands:
  craftcontrol:
    description: Lists every item with crafting disabled
    usage: /craftcontrol list